routes/web.php
<?php

use App\Http\Controllers\Admin\Blog\CategoryController as AdminCategoryController;
use App\Http\Controllers\Admin\Blog\PostController as AdminPostController;
use App\Http\Controllers\Admin\Blog\UserController as AdminUserController;
use App\Http\Controllers\Web\Blog\PostController;
use App\Http\Controllers\Web\HomeController;
use App\Http\Controllers\Web\Patterns\BehavioralPatternsController;
use App\Http\Controllers\Web\Patterns\CreationalPatternsController;
use App\Http\Controllers\Web\Patterns\FundamentalPatternsController;
use App\Http\Controllers\Web\Patterns\StructuralPatternsController;
use Illuminate\Support\Facades\Route;

Auth::routes();

Route::get('/', function () {
    return view('plugin/index');
});

Route::middleware('auth')->group(function () {
    // --- Main Page ---
    Route::get('/home', [HomeController::class, 'index'])->name('home');

    // --- Blog ---
    Route::prefix('blog')->group(function () {
        Route::resource('/posts', PostController::class)
            ->names('blog.posts');
    });

    // --- Admin panel ---
    Route::prefix('admin')->group(function () {
        Route::resource('blog/categories', AdminCategoryController::class)
            ->only(['index', 'edit', 'update', 'create', 'store'])
            ->names('admin.blog.categories');
        Route::resource('blog/posts', AdminPostController::class)
            ->except(['show'])
            ->names('admin.blog.posts');

        Route::get('user/excel', [AdminUserController::class, 'excel'])
            ->name('admin.user.excel');
    });

    // --- Patterns ---
    Route::prefix('patterns')->group(function () {

        // ---------- Fundamental
        Route::get('/property-container', [FundamentalPatternsController::class, 'PropertyContainer'])
            ->name('patterns.property-container');
        Route::get('/delegation', [FundamentalPatternsController::class, 'Delegation'])
            ->name('patterns.delegation');
        Route::get('/event-channel', [FundamentalPatternsController::class, 'EventChannel'])
            ->name('patterns.event-channel');
        Route::get('/interface', [FundamentalPatternsController::class, 'InterfacePattern'])
            ->name('patterns.interface');

        // ---------- Creational
        Route::get('/abstract-factory', [CreationalPatternsController::class, 'AbstractFactory'])
            ->name('patterns.abstract-factory');
        Route::get('/factory-method', [CreationalPatternsController::class, 'FactoryMethod'])
            ->name('patterns.factory-method');
        Route::get('/static-factory', [CreationalPatternsController::class, 'StaticFactory'])
            ->name('patterns.static-factory');
        Route::get('/simple-factory', [CreationalPatternsController::class, 'SimpleFactory'])
            ->name('patterns.simple-factory');
        Route::get('/singleton', [CreationalPatternsController::class, 'Singleton'])
            ->name('patterns.singleton');
        Route::get('/multiton', [CreationalPatternsController::class, 'Multiton'])
            ->name('patterns.multiton');
        Route::get('/builder', [CreationalPatternsController::class, 'Builder'])
            ->name('patterns.builder');
        Route::get('/lazy-initialization', [CreationalPatternsController::class, 'LazyInitialization'])
            ->name('patterns.lazy-initialization');
        Route::get('/prototype', [CreationalPatternsController::class, 'Prototype'])
            ->name('patterns.prototype');
        Route::get('/object-pool', [CreationalPatternsController::class, 'ObjectPool'])
            ->name('patterns.object-pool');

        // ---------- Structural
        Route::get('/adapter', [StructuralPatternsController::class, 'Adapter'])
            ->name('patterns.adapter');
        Route::get('/facade', [StructuralPatternsController::class, 'Facade'])
            ->name('patterns.facade');
        Route::get('/bridge', [StructuralPatternsController::class, 'Bridge'])
            ->name('patterns.bridge');
        Route::get('/composite', [StructuralPatternsController::class, 'Composite'])
            ->name('patterns.composite');

        // ---------- Behavioral
        Route::get('/strategy', [BehavioralPatternsController::class, 'Strategy'])
            ->name('patterns.strategy');
    });
});

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Auth::routes();

app/Http/Controllers/Admin/Blog/BaseController.php
<?php

namespace App\Http\Controllers\Admin\Blog;

use App\Http\Controllers\Controller;

abstract class BaseController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }
}

app/Http/Controllers/Admin/Blog/CategoryController.php
<?php

namespace App\Http\Controllers\Admin\Blog;

use App\Http\Requests\Blog\BlogCategoryCreateRequest;
use App\Http\Requests\Blog\BlogCategoryUpdateRequest;
use App\Models\BlogCategory;
use App\Repositories\Admin\BlogCategoryRepository;
use Illuminate\Contracts\View\View;
use Illuminate\Http\RedirectResponse;

/**
 * Управление категориями блога
 *
 * @package App\Http\Controllers\Blog\Admin
 */
class CategoryController extends BaseController
{
    /**
     * Display a listing of the resource.
     *
     * @return View
     */
    public function index(BlogCategoryRepository $blogCategoryRepository)
    {
        $paginator = $blogCategoryRepository->getAllWithPaginate(5);
        return view('admin.blog.categories.index', compact('paginator'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return View
     */
    public function create(BlogCategoryRepository $blogCategoryRepository)
    {
        $item = new BlogCategory();
        $categoryList = $blogCategoryRepository->getForComboBox();
        return view('admin.blog.categories.create', compact('item', 'categoryList'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param BlogCategoryCreateRequest $request
     * @return RedirectResponse
     */
    public function store(BlogCategoryCreateRequest $request)
    {
        $data = $request->input();

        if ($item = (new BlogCategory())->query()->create($data)) {
            return redirect()
                ->route('admin.blog.categories.edit', $item->id)
                ->with(['success' => 'Успешно Сохранен.']);
        } else {
            return back()
                ->withErrors(['msg' => "Ошибка сохранения."])
                ->withInput();
        }
    }

    /**
     * Display the specified resource.
     *
     * @param int $id
     * @return void
     */
    public function show($id)
    {
        dd(__METHOD__);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     * @param BlogCategoryRepository $blogCategoryRepository
     * @return View
     */
    public function edit(int $id, BlogCategoryRepository $blogCategoryRepository)
    {
        if (!$item = $blogCategoryRepository->getEdit($id)) {
            abort(404);
        }
        if (!$categoryList = $blogCategoryRepository->getForComboBox()) {
            abort(404);
        }

        return view('admin.blog.categories.edit', compact('item', 'categoryList'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param BlogCategoryUpdateRequest $request
     * @param int $id
     * @return RedirectResponse
     */
    public function update(int $id, BlogCategoryUpdateRequest $request, BlogCategoryRepository $blogCategoryRepository)
    {
        if (empty($item = $blogCategoryRepository->getEdit($id))) {
            return back()->withErrors(['msg' => "Запись id=[{$id}] не найдена."])->withInput();
        }

        $data = $request->all();

        if ($item->update($data)) {
            return redirect()->route('admin.blog.categories.edit', $item->id)->with(['success' => 'Успешно Сохранен.']);
        } else {
            return back()->withErrors(['msg' => "Ошибка сохранения."])->withInput();
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     * @return RedirectResponse
     */
    public function destroy(int $id)
    {
        // soft delete
        $result = BlogCategory::destroy($id);
        // full delete
//        $result = BlogCategory::query()->find($id)->forceDelete();

        if ($result) {
            return redirect()->route('admin.blog.posts.index')->with(['success' => "Запись [$id] удалена"]);
        } else {
            return back()->withErrors(['msg' => "Ошибка удаления."])->withInput();
        }
    }
}

app/Http/Controllers/Admin/Blog/PostController.php
<?php


namespace App\Http\Controllers\Admin\Blog;

use App\Http\Requests\Blog\BlogPostCreateRequest;
use App\Http\Requests\Blog\BlogPostUpdateRequest;
use App\Jobs\BlogPostAfterCreateJob;
use App\Jobs\BlogPostAfterDeleteJob;
use App\Models\BlogPost;
use App\Repositories\Admin\BlogCategoryRepository;
use App\Repositories\Admin\BlogPostRepository;
use Illuminate\Http\RedirectResponse;

/**
 * Blog Articles Management
 * @package App\Http\Controllers\Blog\Admin
 */
class PostController extends BaseController
{
    /**
     * Display a listing of the resource.
     */
    public function index(BlogPostRepository $blogPostRepository)
    {
        $paginator = $blogPostRepository->getAllWithPagination();
        return view('admin.blog.posts.index', compact('paginator'));
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create(BlogCategoryRepository $blogCategoryRepository)
    {
        $item = new BlogPost();
        $categoryList = $blogCategoryRepository->getForComboBox();
        return view('admin.blog.posts.edit', compact('item', 'categoryList'));
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(BlogPostCreateRequest $request)
    {
        $data = $request->input();
        $item =  BlogPost::query()->create($data);
        if ($item) {
            $job = new BlogPostAfterCreateJob($item);
            $this->dispatch($job);
            return redirect()
                ->route('admin.blog.posts.edit', $item->id)
                ->with(['success' => 'Успешно Сохранен.']);
        } else {
            return back()
                ->withErrors(['msg' => "Ошибка сохранения."])
                ->withInput();
        }
    }

    /**
     * Display the specified resource.
     */
    public function show()
    {
        dd(__METHOD__);
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit($id, BlogPostRepository $blogPostRepository, BlogCategoryRepository $blogCategoryRepository)
    {
        if (!$item = $blogPostRepository->getEdit($id)) {
            abort(404);
        }
        if (!$categoryList = $blogCategoryRepository->getForComboBox()) {
            abort(404);
        }
        return view('admin.blog.posts.edit', compact('item', 'categoryList'));
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(BlogPostUpdateRequest $request, $id, BlogPostRepository $blogPostRepository)
    {
        if (!$item = $blogPostRepository->getEdit($id)) {
            return back()->withErrors(['msg' => "Запись id=[{$id}] не найдена"])->withInput();
        }

        $data = $request->all();

        if ($result = $item->update($data)) {
            return redirect()->route('admin.blog.posts.edit', $item->id)->with(['success' => 'Успешно сохранено']);
        } else {
            return back()->withErrors(['msg' => "Ошибка сохранения."])->withInput();
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     * @return RedirectResponse
     */
    public function destroy($id)
    {
        if ($result = BlogPost::destroy($id)) {
            BlogPostAfterDeleteJob::dispatch($id);

            return redirect()->route('admin.blog.posts.index')->with(['success' => "Запись [$id] удалена"]);
        } else {
            return back()->withErrors(['msg' => "Ошибка удаления."])->withInput();
        }
    }
}

app/Http/Controllers/Admin/Blog/UserController.php
<?php

namespace App\Http\Controllers\Admin\Blog;

use App\Exports\ExportExcel;
use App\Services\UserService;
use Maatwebsite\Excel\Facades\Excel;
use PhpOffice\PhpSpreadsheet\Exception;
use Symfony\Component\HttpFoundation\BinaryFileResponse;

class UserController extends BaseController
{
    /**
     * Download excel file
     *
     * @return BinaryFileResponse
     * @throws Exception
     */
    public function excel(UserService $service)
    {
        $users = $service->getUsersForExcel();
        $fileName = 'Users_' . now()->format('Y-m-d') . '.xlsx';
        return Excel::download(new ExportExcel($users), $fileName);
    }
}

app/Http/Controllers/Web/Blog/BaseController.php
<?php

namespace App\Http\Controllers\Web\Blog;

use App\Http\Controllers\Controller;

abstract class BaseController extends Controller
{

}

app/Http/Controllers/Web/Blog/PostController.php
<?php

namespace App\Http\Controllers\Web\Blog;

use App\Models\BlogPost;
use Illuminate\Contracts\View\View;

class PostController extends BaseController
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return View
     */
    public function index()
    {
        $items = BlogPost::query()->paginate(25);
        return view('web.blog.posts.index', compact('items'));
    }
}

resources/views/admin/blog/posts/edit.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    @if($item->exists)
                        <h1>Edit: {{$item->id}}</h1>
                    @else
                        <h1>Create</h1>
                    @endif

                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="#">admin</a></li>
                        <li class="breadcrumb-item"><a href="#">blog</a></li>
                        <li class="breadcrumb-item"><a href="#">posts</a></li>
                        @if($item->exists)
                            <li class="breadcrumb-item active">Edit: {{$item->id}}</li>
                        @else
                            <li class="breadcrumb-item active">Create</li>
                        @endif
                    </ol>
                </div>
            </div>
        </div>
    </section>

    @include('includes.result_messages')

    <div class="container-fluid">
        @php /** @var \App\Models\BlogCategory $item */ @endphp
        @if($item->exists)
            <form action="{{ route('admin.blog.posts.update', $item->id) }}" method="POST">
                @method('PATCH')
                @else
                    <form action="{{ route('admin.blog.posts.store') }}" method="POST">
                        @endif
                        @csrf
                        <div class="row">
                            <div class="col-md-6">
                                <div class="card card-primary card-outline card-tabs">
                                    <div class="card-header ">
                                        <h3 class="card-title">
                                            @if($item->is_published) Опубликовано @else Не опубликовано @endif
                                        </h3>
                                    </div>
                                    <div class="card-header p-0 pt-1 border-bottom-0">
                                        <ul class="nav nav-tabs" id="custom-tabs-three-tab" role="tablist">
                                            <li class="nav-item">
                                                <a class="nav-link active" id="custom-tabs-three-home-tab"
                                                   data-toggle="pill" href="#custom-tabs-three-home" role="tab"
                                                   aria-controls="custom-tabs-three-home"
                                                   aria-selected="true">Основные данные</a>
                                            </li>
                                            <li class="nav-item">
                                                <a class="nav-link" id="custom-tabs-three-profile-tab"
                                                   data-toggle="pill" href="#custom-tabs-three-profile" role="tab"
                                                   aria-controls="custom-tabs-three-profile"
                                                   aria-selected="false">Дополнительные данные</a>
                                            </li>
                                        </ul>
                                    </div>
                                    <div class="card-body">
                                        <div class="tab-content" id="custom-tabs-three-tabContent">
                                            <div class="tab-pane fade active show" id="custom-tabs-three-home"
                                                 role="tabpanel" aria-labelledby="custom-tabs-three-home-tab">
                                                <div class="form-group">
                                                    <label for="title">Заголовок</label>
                                                    <input type="text" name="title" id="title" value="{{$item->title}}"
                                                           autocomplete="title" class="form-control">
                                                </div>
                                                <div class="form-group">
                                                    <label for="content_raw">Статья</label>
                                                    <textarea name="content_raw" id="content_raw"
                                                              class="form-control" autocomplete="content_raw"
                                                              rows="10">{{ old('content_raw', $item->content_raw) }}</textarea>
                                                </div>
                                            </div>
                                            <div class="tab-pane fade" id="custom-tabs-three-profile" role="tabpanel"
                                                 aria-labelledby="custom-tabs-three-profile-tab">

                                                <div class="form-group">
                                                    <label for="slug">Идентификатор</label>
                                                    <input type="text" name="slug" id="slug" value="{{$item->slug}}"
                                                           autocomplete="slug" class="form-control">
                                                </div>

                                                <div class="form-group">
                                                    <label for="category_id">Категория</label>
                                                    <select id="category_id" name="category_id" autocomplete="category_id"
                                                            class="form-control">

                                                        @foreach($categoryList as $category)
                                                            @if($item->category_id == $category->id)
                                                                <option value="{{$category->id}}" selected>
                                                                    {{$category->id_title}}
                                                                </option>
                                                            @else
                                                                <option
                                                                    value="{{$category->id}}">{{$category->id_title}}</option>
                                                            @endif
                                                        @endforeach

                                                    </select>

                                                    <div class="form-group">
                                                        <label for="excerpt">Выдержка</label>
                                                        <textarea name="excerpt" id="excerpt"
                                                                  class="form-control" autocomplete="excerpt"
                                                                  rows="4">{{ old('excerpt', $item->excerpt) }}</textarea>
                                                    </div>
                                                    <div class="form-group">
                                                        <div class="custom-control custom-checkbox">
                                                            <input type="hidden" name="is_published" value="0">

                                                            <input class="custom-control-input" name="is_published"
                                                                   type="checkbox" id="customCheckbox1"
                                                                   value="1"
                                                                   @if($item->is_published) checked @endif>
                                                            <label for="customCheckbox1" class="custom-control-label">
                                                                Опубликовано
                                                            </label>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div class="col-md-6">
                                <div class="card card-default">
                                    <div class="card-body">
                                        <button type="submit" class="btn btn-primary">Сохранить</button>
                                        @if($item->exists)
                                            </form>
                                            <form class="float-right" action="{{ route('admin.blog.posts.destroy', $item->id) }}" method="POST">
                                                @method('DELETE')
                                                @csrf
                                                <button type="submit" class="btn btn-danger right">Удалить</button>
                                            </form>
                                        @endif
                                    </div>
                                </div>
                                @if($item->exists)
                                    <div class="card card-default">
                                        <div class="card-body">
                                            ID: {{$item->id}}
                                        </div>
                                    </div>
                                    <div class="card card-default">
                                        <div class="card-body">
                                            <div class="form-group">
                                                <label for="created_at">Создано</label>
                                                <input for="created_at" type="text" name="created_at" id="created_at"
                                                       value="{{$item->created_at}}" autocomplete="created_at"
                                                       class="form-control"
                                                       disabled="disabled">
                                            </div>

                                            <div class="form-group">
                                                <label for="updated_at">Изменено</label>
                                                <input for="updated_at" type="text" name="updated_at" id="updated_at"
                                                       value="{{$item->updated_at}}" autocomplete="updated_at"
                                                       class="form-control"
                                                       disabled="disabled">
                                            </div>

                                            <div class="form-group">
                                                <label for="deleted_at">Опубликовано</label>
                                                <input for="deleted_at" type="text" name="deleted_at" id="deleted_at"
                                                       value="{{$item->published_at}}" autocomplete="deleted_at"
                                                       class="form-control"
                                                       disabled="disabled">
                                            </div>

                                            <div class="form-group">
                                                <label for="deleted_at">Удалено</label>
                                                <input for="deleted_at" type="text" name="deleted_at" id="deleted_at"
                                                       value="{{$item->deleted_at}}" autocomplete="deleted_at"
                                                       class="form-control"
                                                       disabled="disabled">
                                            </div>
                                        </div>
                                    </div>
                                @endif
                            </div>
                        </div>
                    </div>
                </form>
@endsection