routes/web.php
<?php

use App\Http\Controllers\Admin\Blog\CategoryController as AdminCategoryController;
use App\Http\Controllers\Admin\Blog\PostController as AdminPostController;
use App\Http\Controllers\Admin\Blog\UserController as AdminUserController;
use App\Http\Controllers\Web\Blog\PostController;
use App\Http\Controllers\Web\HomeController;
use App\Http\Controllers\Web\Patterns\BehavioralPatternsController;
use App\Http\Controllers\Web\Patterns\CreationalPatternsController;
use App\Http\Controllers\Web\Patterns\FundamentalPatternsController;
use App\Http\Controllers\Web\Patterns\StructuralPatternsController;
use Illuminate\Support\Facades\Route;

Auth::routes();

Route::get('/', function () {
    return view('plugin/index');
});

Route::middleware('auth')->group(function () {
    // --- Main Page ---
    Route::get('/home', [HomeController::class, 'index'])->name('home');

    // --- Blog ---
    Route::prefix('blog')->group(function () {
        Route::resource('/posts', PostController::class)
            ->names('blog.posts');
    });

    // --- Admin panel ---
    Route::prefix('admin')->group(function () {
        Route::resource('blog/categories', AdminCategoryController::class)
            ->only(['index', 'edit', 'update', 'create', 'store'])
            ->names('admin.blog.categories');
        Route::resource('blog/posts', AdminPostController::class)
            ->except(['show'])
            ->names('admin.blog.posts');

        Route::get('user/excel', [AdminUserController::class, 'excel'])
            ->name('admin.user.excel');
    });

    // --- Patterns ---
    Route::prefix('patterns')->group(function () {

        // ---------- Fundamental
        Route::get('/property-container', [FundamentalPatternsController::class, 'PropertyContainer'])
            ->name('patterns.property-container');
        Route::get('/delegation', [FundamentalPatternsController::class, 'Delegation'])
            ->name('patterns.delegation');
        Route::get('/event-channel', [FundamentalPatternsController::class, 'EventChannel'])
            ->name('patterns.event-channel');
        Route::get('/interface', [FundamentalPatternsController::class, 'InterfacePattern'])
            ->name('patterns.interface');

        // ---------- Creational
        Route::get('/abstract-factory', [CreationalPatternsController::class, 'AbstractFactory'])
            ->name('patterns.abstract-factory');
        Route::get('/factory-method', [CreationalPatternsController::class, 'FactoryMethod'])
            ->name('patterns.factory-method');
        Route::get('/static-factory', [CreationalPatternsController::class, 'StaticFactory'])
            ->name('patterns.static-factory');
        Route::get('/simple-factory', [CreationalPatternsController::class, 'SimpleFactory'])
            ->name('patterns.simple-factory');
        Route::get('/singleton', [CreationalPatternsController::class, 'Singleton'])
            ->name('patterns.singleton');
        Route::get('/multiton', [CreationalPatternsController::class, 'Multiton'])
            ->name('patterns.multiton');
        Route::get('/builder', [CreationalPatternsController::class, 'Builder'])
            ->name('patterns.builder');
        Route::get('/lazy-initialization', [CreationalPatternsController::class, 'LazyInitialization'])
            ->name('patterns.lazy-initialization');
        Route::get('/prototype', [CreationalPatternsController::class, 'Prototype'])
            ->name('patterns.prototype');
        Route::get('/object-pool', [CreationalPatternsController::class, 'ObjectPool'])
            ->name('patterns.object-pool');

        // ---------- Structural
        Route::get('/adapter', [StructuralPatternsController::class, 'Adapter'])
            ->name('patterns.adapter');
        Route::get('/facade', [StructuralPatternsController::class, 'Facade'])
            ->name('patterns.facade');
        Route::get('/bridge', [StructuralPatternsController::class, 'Bridge'])
            ->name('patterns.bridge');
        Route::get('/composite', [StructuralPatternsController::class, 'Composite'])
            ->name('patterns.composite');

        // ---------- Behavioral
        Route::get('/strategy', [BehavioralPatternsController::class, 'Strategy'])
            ->name('patterns.strategy');
    });
});

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Auth::routes();

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ config('app.name') }}</title>
    <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.14.0/css/all.min.css"
          integrity="sha512-1PKOgIY59xJ8Co8+NE6FZ+LOAZKjy+KY8iq0G4B3CyeY6wYHN3yt9PW0XpSriVlkMXe40PTKnXrLnZ9+fkDaog=="
          crossorigin="anonymous"/>

    <link href="{{ mix('css/app.css') }}" rel="stylesheet">

    @stack('third_party_stylesheets')

    @stack('page_css')
</head>

<body class="hold-transition sidebar-mini layout-fixed">
<div class="wrapper">
    <!-- Main Header -->
    <nav class="main-header navbar navbar-expand navbar-white navbar-light">
        <!-- Left navbar links -->
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
            </li>
        </ul>

        <ul class="navbar-nav ml-auto">
            @if (Route::has('login'))
                @auth
                    <li class="nav-item dropdown user-menu">
                        <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown">
                            <img src="/img/laravel_logo.png"
                                 class="user-image img-circle elevation-2" alt="User Image">
                            <span class="d-none d-md-inline">{{ Auth::user()->name ?? 'unauthorized' }}</span>
                        </a>
                        <ul class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
                            <!-- User image -->
                            <li class="user-header bg-primary">
                                <img src="/img/laravel_logo.png"
                                     class="img-circle elevation-2"
                                     alt="User Image">
                                <p>
                                    {{ Auth::user()->name  ?? 'unauthorized'}}
                                    @auth
                                        <small>Member since {{ Auth::user()->created_at->format('M. Y') }}</small>
                                    @endauth
                                </p>
                            </li>
                            <!-- Menu Footer-->
                            <li class="user-footer">
                                <a href="#" class="btn btn-default btn-flat">Profile</a>
                                <a href="#" class="btn btn-default btn-flat float-right"
                                   onclick="event.preventDefault(); document.getElementById('logout-form').submit();">
                                    Sign out
                                </a>
                                <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                    @csrf
                                </form>
                            </li>
                        </ul>
                    </li>
                @else
                    <a href="{{ route('login') }}" class="text-sm text-gray-700 underline">Log in</a>

                    @if (Route::has('register'))
                        <a href="{{ route('register') }}" class="ml-4 text-sm text-gray-700 underline">Register</a>
                    @endif
                @endauth
            @endif
        </ul>
    </nav>

    <!-- Left side column. contains the logo and sidebar -->
@include('layouts.sidebar')

<!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        @yield('content')
    </div>

    <!-- Main Footer -->
    <footer class="main-footer">
        <div class="float-right d-none d-sm-block">
            <b>Version</b> 3.0.5
        </div>
        <strong>Copyright &copy; 2014-2022 <a href="https://adminlte.io">AdminLTE.io</a>.</strong> All rights
        reserved.
    </footer>
</div>

<script src="{{ mix('js/app.js') }}"></script>

@stack('third_party_scripts')

@stack('page_scripts')
</body>
</html>

resources/views/layouts/menu.blade.php
<!-- need to remove -->
<li class="nav-item">
    <a target="_blank" href="https://adminlte.io/themes/v3/index.html" class="nav-link">
        <i class="nav-icon fas fa-external-link-alt"></i>
        <p>adminlte.io</p>
    </a>
</li>
<li class="nav-item">
    <a href="{{ route('home') }}" class="nav-link">
        <i class="nav-icon fas fa-home"></i>
        <p>Home</p>
    </a>
</li>

<li class="nav-item">
    <a href="#" class="nav-link">
        <i class="nav-icon fas fa-book"></i>
        <p>
            Patterns
            <i class="fas fa-angle-left right"></i>
        </p>
    </a>
    <ul class="nav nav-treeview">
        <li class="nav-item">
            <a href="#" class="nav-link">
                <i class="far fa-circle nav-icon"></i>
                <p>Fundamental</p>
                <i class="right fas fa-angle-left"></i>
            </a>
            <ul class="nav nav-treeview">
                <li class="nav-item">
                    <a href="{{ route('patterns.property-container') }}" class="nav-link">
                        <i class="far fa-dot-circle nav-icon"></i>
                        <p>Property container</p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{{ route('patterns.delegation') }}" class="nav-link">
                        <i class="far fa-dot-circle nav-icon"></i>
                        <p>Delegation</p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{{ route('patterns.event-channel') }}" class="nav-link">
                        <i class="far fa-dot-circle nav-icon"></i>
                        <p>Event channel</p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{{ route('patterns.interface') }}" class="nav-link">
                        <i class="far fa-dot-circle nav-icon"></i>
                        <p>Interface Pattern</p>
                    </a>
                </li>
            </ul>
        </li>
        <li class="nav-item">
            <a href="#" class="nav-link">
                <i class="far fa-circle nav-icon"></i>
                <p>Creational</p>
                <i class="right fas fa-angle-left"></i>
            </a>
            <ul class="nav nav-treeview">
                <li class="nav-item">
                    <a href="{{ route('patterns.abstract-factory') }}" class="nav-link">
                        <i class="far fa-dot-circle nav-icon"></i>
                        <p>Abstract factory</p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{{ route('patterns.factory-method') }}" class="nav-link">
                        <i class="far fa-dot-circle nav-icon"></i>
                        <p>Factory method</p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{{ route('patterns.static-factory') }}" class="nav-link">
                        <i class="far fa-dot-circle nav-icon"></i>
                        <p>Static factory</p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{{ route('patterns.simple-factory') }}" class="nav-link">
                        <i class="far fa-dot-circle nav-icon"></i>
                        <p>Simple factory</p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{{ route('patterns.singleton') }}" class="nav-link">
                        <i class="far fa-dot-circle nav-icon"></i>
                        <p>Singleton</p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{{ route('patterns.multiton') }}" class="nav-link">
                        <i class="far fa-dot-circle nav-icon"></i>
                        <p>Multiton</p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{{ route('patterns.builder') }}" class="nav-link">
                        <i class="far fa-dot-circle nav-icon"></i>
                        <p>Builder</p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{{ route('patterns.lazy-initialization') }}" class="nav-link">
                        <i class="far fa-dot-circle nav-icon"></i>
                        <p>Lazy initialization</p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{{ route('patterns.prototype') }}" class="nav-link">
                        <i class="far fa-dot-circle nav-icon"></i>
                        <p>Prototype</p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{{ route('patterns.object-pool') }}" class="nav-link">
                        <i class="far fa-dot-circle nav-icon"></i>
                        <p>Object pool</p>
                    </a>
                </li>
            </ul>
        </li>
        <li class="nav-item">
            <a href="#" class="nav-link">
                <i class="far fa-circle nav-icon"></i>
                <p>Structural</p>
                <i class="right fas fa-angle-left"></i>
            </a>
            <ul class="nav nav-treeview">
                <li class="nav-item">
                    <a href="{{ route('patterns.adapter') }}" class="nav-link">
                        <i class="far fa-dot-circle nav-icon"></i>
                        <p>Adapter</p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{{ route('patterns.facade') }}" class="nav-link">
                        <i class="far fa-dot-circle nav-icon"></i>
                        <p>Facade</p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{{ route('patterns.bridge') }}" class="nav-link">
                        <i class="far fa-dot-circle nav-icon"></i>
                        <p>Bridge</p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{{ route('patterns.composite') }}" class="nav-link">
                        <i class="far fa-dot-circle nav-icon"></i>
                        <p>Composite</p>
                    </a>
                </li>
            </ul>
        </li>
        <li class="nav-item">
            <a href="#" class="nav-link">
                <i class="far fa-circle nav-icon"></i>
                <p>Behavioral</p>
                <i class="right fas fa-angle-left"></i>
            </a>
            <ul class="nav nav-treeview" >
                <li class="nav-item">
                    <a href="{{ route('patterns.strategy') }}" class="nav-link">
                        <i class="far fa-dot-circle nav-icon"></i>
                        <p>Strategy</p>
                    </a>
                </li>
            </ul>
        </li>
    </ul>
</li>

@auth
    <li class="nav-item">
        <a href="#" class="nav-link">
            <i class="nav-icon fas fa-edit"></i>
            <p>
                Admin
                <i class="fas fa-angle-left right"></i>
            </p>
        </a>
        <ul class="nav nav-treeview">
            <li class="nav-item">
                <a href="{{ route('admin.blog.categories.index') }}" class="nav-link">
                    <i class="far fa-circle nav-icon"></i>
                    <p>categories</p>
                </a>
            </li>
            <li class="nav-item">
                <a href="{{ route('admin.blog.posts.index') }}" class="nav-link">
                    <i class="far fa-circle nav-icon"></i>
                    <p>posts</p>
                </a>
            </li>
        </ul>
    </li>
@endauth

resources/views/layouts/sidebar.blade.php
<aside class="main-sidebar sidebar-dark-primary elevation-4">
    <a href="{{ route('home') }}" class="brand-link">
        <img src="/img/laravel_logo.png"
             alt="AdminLTE Logo"
             class="brand-image img-circle elevation-3">
        <span class="brand-text font-weight-light">{{ config('app.name') }}</span>
    </a>

    <div class="sidebar">
        <nav class="mt-2">
            <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                @include('layouts.menu')
            </ul>
        </nav>
    </div>

</aside>

resources/views/layouts/simple.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Fonts -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Nunito:wght@400;600;700&display=swap">

    <!-- Styles -->
    <link rel="stylesheet" href="{{ asset('css/app.css') }}">

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>
</head>
<body class="font-sans antialiased">
<div class="min-h-screen bg-gray-100">
@include('layouts.navigation')

<!-- Page Heading -->
    @if(isset($header))
        <header class="bg-white shadow">
            <div class="max-w-7xl mx-auto py-6 px-4 sm:px-6 lg:px-8">
                {{ $header ?? '' }}
            </div>
        </header>
    @endif
<!-- Page Content -->
    <main>
        {{ $slot ?? '' }}
        @yield('content')
    </main>
</div>
</body>
</html>